import = ["/Users/chris.pymm/.config/alacritty/themes/themes/dracula.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 18

[font.normal]
family = "BlexMono Nerd Font"
style = "Light"

[font.offset]
x = 0
y = 10

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 1.0
blur = false
padding.x = 10
padding.y = 10

[[keyboard.bindings]]
chars = "#"
key = "Key3"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0013,"
key = "Comma"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0013K"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = """
lfcd
"""
key = "F"
mods = "Command"

[[keyboard.bindings]]
chars = """
:GitFiles
"""
key = "P"
mods = "Command"

[[keyboard.bindings]]
chars = """
:Commands
"""
key = "P"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0013g"
key = "G"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0013s"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00131"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00132"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00133"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00134"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00135"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00136"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00137"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00138"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00139"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0013L"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0013["
key = "LBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0013p"
key = "LBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0013u"
key = "O"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0013%"
key = "E"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0013\""
key = "E"
mods = "Command"

[[keyboard.bindings]]
chars = """
:q
"""
key = "Q"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0013n"
key = "RBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = """
:w
"""
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = """
:wa
"""
key = "S"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0013:"
key = "Semicolon"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0013c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0013!"
key = "T"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0013T"
key = "J"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0013x"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0013z"
key = "Z"
mods = "Command"

