#!/usr/bin/env sh

#sudo yabai --load-sa
#yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  15
yabai -m config bottom_padding               15
yabai -m config left_padding                 15
yabai -m config right_padding                15
yabai -m config window_gap                   15
yabai -m config external_bar                 all:0:32


# Space labels
yabai -m space 1 --label "Code"
yabai -m space 2 --label "Firefox"
yabai -m space 3 --label "Chrome"
yabai -m space 4 --label "Slack"
yabai -m space 5 --label "Mail"
yabai -m space 6 --label "Figma"
yabai -m space 7 --label "Notes"
yabai -m space 8 --label "Music"
yabai -m space 9 --label "Misc"

# apps to not manage (ignore)
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Activity Monitor$" layer=above manage=off
yabai -m rule --add app="^Messages$" manage=off
yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add app="^Lastpass$" manage=off
yabai -m rule --add app="^Logitech G HUB$" manage=off
yabai -m rule --add app="^Looking Glass" manage="off"
#yabai -m rule --add app="^Alfred Preferences$" manage=off

# yabai -m signal --add event=space_changed \
#     action="osascript -e 'tell application \"Übersicht\" to refresh'"

echo "yabai configuration loaded.."
